"""Widen ml_model_versions.version from VARCHAR(32) to VARCHAR(64).

The VARCHAR(32) limit defined in migration 0001 is insufficient for
version strings generated by persist.py (e.g.
``random_forest-v1-20260912T081512Z`` = 37 chars).  VARCHAR(64) provides
comfortable headroom for all realistic ``<algorithm>-v<n>-<timestamp>``
formats.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-12
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column(
        "ml_model_versions",
        "version",
        type_=sa.String(64),
        existing_type=sa.String(32),
        existing_nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        "ml_model_versions",
        "version",
        type_=sa.String(32),
        existing_type=sa.String(64),
        existing_nullable=False,
    )
